#ifndef DRIVERLIB_ALL_H
#define DRIVERLIB_ALL_H

// Stellaris hardware includes
//#include "inc/asmdefs.h"
#include "inc/hw_adc.h"
#include "inc/hw_can.h"
#include "inc/hw_comp.h"
#include "inc/hw_eeprom.h"
#include "inc/hw_epi.h"
#include "inc/hw_ethernet.h"
#include "inc/hw_fan.h"
#include "inc/hw_flash.h"
#include "inc/hw_gpio.h"
#include "inc/hw_hibernate.h"
#include "inc/hw_i2c.h"
#include "inc/hw_i2s.h"
#include "inc/hw_ints.h"
#include "inc/hw_lpc.h"
#include "inc/hw_memmap.h"
#include "inc/hw_nvic.h"
#include "inc/hw_peci.h"
#include "inc/hw_pwm.h"
#include "inc/hw_qei.h"
#include "inc/hw_ssi.h"
#include "inc/hw_sysctl.h"
#include "inc/hw_sysexc.h"
#include "inc/hw_timer.h"
#include "inc/hw_types.h"
#include "inc/hw_uart.h"
#include "inc/hw_udma.h"
#include "inc/hw_usb.h"
#include "inc/hw_watchdog.h"


// Driverlib includes
#include "driverlib/adc.h"
#include "driverlib/can.h"
#include "driverlib/comp.h"
#include "driverlib/cpu.h"
#include "driverlib/debug.h"
#include "driverlib/eeprom.h"
#include "driverlib/epi.h"
#include "driverlib/ethernet.h"
#include "driverlib/fan.h"
#include "driverlib/flash.h"
#include "driverlib/fpu.h"
#include "driverlib/gpio.h"
#include "driverlib/hibernate.h"
#include "driverlib/i2c.h"
#include "driverlib/i2s.h"
#include "driverlib/interrupt.h"
#include "driverlib/lpc.h"
#include "driverlib/mpu.h"
#include "driverlib/peci.h"
#include "driverlib/pin_map.h"
#include "driverlib/pwm.h"
#include "driverlib/qei.h"
#include "driverlib/rom.h"
#include "driverlib/rom_map.h"
#include "driverlib/rtos_bindings.h"
#include "driverlib/ssi.h"
#include "driverlib/sysctl.h"
#include "driverlib/sysexc.h"
#include "driverlib/systick.h"
#include "driverlib/timer.h"
#include "driverlib/uart.h"
#include "driverlib/udma.h"
#include "driverlib/usb.h"
#include "driverlib/watchdog.h"

#endif // DRIVERLIB_ALL_H
